language: generic

services:
  - docker

matrix:
  include:
    - env: ROS_DISTRO=kinetic
    - env: ROS_DISTRO=lunar
    - env: ROS_DISTRO=melodic

before_install:
- docker build . -t kitti2bag --build-arg ROS_DISTRO=${ROS_DISTRO}

script:
- docker run --entrypoint '/bin/bash' kitti2bag -c '
    source /opt/ros/$ROS_DISTRO/setup.bash &&
    cd /kitti2bag &&
    python setup.py test --addopts=-svv
  '
